### ISSUE TITLE
InvaildKeyException when init Digitus

### ISSUE THREAD

**Issue by WindSekirun** [afollestad/digitus#11]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of this library.
- [x] I have given my issue a non-generic title.
###### Include the following:
- Library version: `0.2.1.2`
- Device OS version: `6.0.1`
- Device Manufacturer: `Samsung`
- Device Name: `SM-G925S`
- Target SDK: 24 (Android 7.0)

Main Code

``` java
public void inflateFingerprintView() {
        if (lockVaildUtils.isUseFingerprint()) {
            if (Build.VERSION.SDK_INT >= 23) {
                fingerprintManagerCompat = FingerprintManagerCompat.from(this);
                if (fingerprintManagerCompat.isHardwareDetected()) {
                    if (fingerprintManagerCompat.hasEnrolledFingerprints()) {
                        Digitus.init(this, getString(R.string.app_name), 59, this);
                        Digitus.get().startListening();
                    } else {
                        Toast.makeText(PinLockActivity.this, R.string.fingerprint_not_have_enrolled_fingerprint, Toast.LENGTH_SHORT).show();
                        startActivityForResult(new Intent(android.provider.Settings.ACTION_SETTINGS), 0);
                    }
                }
            }
        }
    }
```

Logcat

``` java
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {.ShapeLockActivity}: java.lang.RuntimeException: Failed to init Cipher
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4156)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4250)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3361)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.RuntimeException: Failed to init Cipher
       at com.afollestad.digitus.MUtils.initCipher(MUtils.java:83)
       at com.afollestad.digitus.DigitusBase.initCipher(DigitusBase.java:75)
       at com.afollestad.digitus.Digitus.startListening(Digitus.java:100)
       at .ShapeLockActivity.inflateFingerprintView(ShapeLockActivity.java:279)
       at .ShapeLockActivity.onResume(ShapeLockActivity.java:526)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1286)
       at android.app.Activity.performResume(Activity.java:6987)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4145)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4250)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3361)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.security.InvalidKeyException: Only SecretKey is supported
       at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:435)
       at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:260)
       at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:612)
       at javax.crypto.Cipher.tryCombinations(Cipher.java:532)
       at javax.crypto.Cipher.getSpi(Cipher.java:437)
       at javax.crypto.Cipher.init(Cipher.java:815)
       at javax.crypto.Cipher.init(Cipher.java:774)
       at com.afollestad.digitus.MUtils.initCipher(MUtils.java:77)
       at com.afollestad.digitus.DigitusBase.initCipher(DigitusBase.java:75)
       at com.afollestad.digitus.Digitus.startListening(Digitus.java:100)
       at .ShapeLockActivity.inflateFingerprintView(ShapeLockActivity.java:279)
       at .ShapeLockActivity.onResume(ShapeLockActivity.java:526)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1286)
       at android.app.Activity.performResume(Activity.java:6987)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4145)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4250)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3361)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
###### Reproduction Steps

Sorry, we don't know how to re-produce this problem. (other device will init successfully)
###### Actual Result

Force Close happened, some user can't use our app.

**Comment by afollestad** [comment]
I will add avoidance for this, but you cannot use this library. Nexus Imprint does not exist on Samsung devices.
