### ISSUE TITLE
Crypto primitive not initialized

### ISSUE THREAD

**Issue by pasha14** [afollestad/digitus#16]
Hi,
I try to use your sample. However, the sample is crashed when i click to open Security Settings button. Here is the crash log:

`java.lang.IllegalStateException: Crypto primitive not initialized
                                                                                  at android.security.keystore.AndroidKeyStoreProvider.getKeyStoreOperationHandle(AndroidKeyStoreProvider.java:163)
                                                                                  at android.hardware.fingerprint.FingerprintManager$CryptoObject.getOpId(FingerprintManager.java:368)
                                                                                  at android.hardware.fingerprint.FingerprintManager.authenticate(FingerprintManager.java:615)
                                                                                  at android.hardware.fingerprint.FingerprintManager.authenticate(FingerprintManager.java:589)
                                                                                  at android.hardware.fingerprint.FingerprintManager.authenticate(FingerprintManager.java:567)
                                                                                  at com.afollestad.digitus.AuthenticationHandler.start(AuthenticationHandler.java:38)
                                                                                  at com.afollestad.digitus.Digitus.startListening(Digitus.java:119)
                                                                                  at com.afollestad.digitussample.MainActivity$2.onClick(MainActivity.java:48)
                                                                                  at android.view.View.performClick(View.java:6207)
                                                                                  at android.widget.TextView.performClick(TextView.java:11094)
                                                                                  at android.view.View$PerformClick.run(View.java:23639)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

My device has Android 7.0 and the brand is Samsung s7 Edge.

**Comment by afollestad** [comment]
This is a Samsung issue that I cannot fix.
